### PR TITLE
Update to upstream master

### PR DESCRIPTION
**Pull request by AlexWayfer**

### CODE REVIEW

**Comment by JelF** [comment]
@AlexWayfer can you instead pull `add_flock_for_cache` in your own fork? I do not want to maintain this fork

**Comment by AlexWayfer** [comment]
Sorry, I didn't understand. I just want to update your PR for `edlebert/money-oxr` repo.

**Comment by JelF** [comment]
> Sorry, I didn't understand. I just want to update your PR for edlebert/money-oxr repo.

Maybe i better close it?

**Comment by AlexWayfer** [comment]
> Maybe i better close it?

As you wish. I just wanted to leave your commit, and I'm not sure that I can do that without your PR, but I can try to do this or copy your code into a new commit from myself with mention you as author.

**Comment by JelF** [comment]
> As you wish. I just wanted to leave your commit, and I'm not sure that I can do that without your PR, but I can try to do this or copy your code into a new commit from myself with mention you as author.

You can either make a PR with my commit or mention me, as your wish

**Pull request closed without merging**
